version: '3.8'

services:
  portfolio:
    build: .
    container_name: stesh-portfolio
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - PORT=8080
      - ENABLE_PORT_80=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

